server:
  port: 9009
spring:
  application:
    name: sns-sms
  rabbitmq:
    host: 192.168.25.133

aliyun:
  sms:
    accessKeyId: LTAIpGYhPa6tmvUO
    accessKeySecret: tTUTTAqzIZx0xfaICzSzZzoKZT1dM0

