server:
  port: 9013
spring:
  application:
    name: sns-encrypt
zuul:
  routes:
    tensquare-base: #基础服务
      path: /base/** #配置请求URL的请求规则
      serviceId: sns-base #指定Eureka注册中心中的服务id
      strip-prefix: true #所有请求都进行转发
      sentiviteHeaders:
      customSensitiveHeaders: true
    tensquare-article: #文章服务
      path: /article/** #配置请求URL的请求规则
      serviceId: sns-article #指定Eureka注册中心中的服务id
      strip-prefix: true
      sentiviteHeaders:
      customSensitiveHeaders: true #让zuul网关处理所有cookie和重定向

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
