server:
  port: 9006
spring:
  application:
    name: sns-spit
  data:
    mongodb:
      host: 192.168.25.133
      database: spitdb
  redis:
    host: 192.168.25.133
jwt:
  config:
    key: zrkworld
    ttl: 3600000

