server:
  port: 9004 #服务访问端口号
spring:
  application:
    name: sns-article #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #服务连接的属性
    url: jdbc:mysql://192.168.25.133:3306/sns_article?characterEncoding=utf-8
    username: root
    password: root
  data: #整合mongodb的配置
    mongodb:
      database: commentdb
      host: 192.168.25.133
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.25.133
  rabbitmq:
    host: 192.168.25.133
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: zrkworld #加盐
    ttl: 3600000 #持续时间